# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=500)),
                ('hash_url', models.CharField(max_length=40)),
                ('short_url', models.CharField(max_length=40)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.CharField(max_length=500)),
                ('analytics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Analytics')),
            ],
        ),
        migrations.AddField(
            model_name='analytics',
            name='url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Url'),
        ),
    ]
